package mk.ukim.finki.masterapplicationsystem.domain.permissions;

public enum PermissionType {
    APPLICATION,
    DOCUMENT_APPLICATION,
    INITIAL_MENTOR_REVIEW,
    STUDENT_SERVICE_REVIEW,
    INITIAL_NNK_REVIEW,
    INITIAL_SECRETARY_REVIEW,
    STUDENT_DRAFT,
    DRAFT_MENTOR_REVIEW,
    DRAFT_SECRETARY_REVIEW,
    DRAFT_NNK_REVIEW,
    SECOND_DRAFT_SECRETARY_REVIEW,
    DRAFT_COMMITTEE_REVIEW,
    STUDENT_CHANGES_DRAFT,
    MENTOR_REPORT,
    REPORT_REVIEW,
    REPORT_SECRETARY_REVIEW,
    REPORT_STUDENT_SERVICE,
    APPLICATION_FINISHED,
    FINISHED
}
